A few more improvements to the README.md
justafish/ddev-drupal-core-dev pull request #13
Opened 2024-03-19 14:13 UTC by rpkoller

I've already created a draft before (https://github.com/justafish/ddev-drupal-core-dev/pull/9) but thanks to my "excellent" git and github skills something went wrong when i tried to sync my branch with the latest changes when randys PR went in. I've simply created a new PR now, that was faster incorporating my suggested changes i've done locally so far. 

and again at first thank you for creating that excellent add-on! and as a disclaimer i am not a developer just a regular ddev user who was just used to a composer patches based workflow for testing issues on drupal.org. when i first tried the add-on i ran into a few stepping blocks since it is following a slightly different paradigm (i've expecting the folder structure with web as the docroot and i've installed drush wondering why i haven't had a `git status` without any changes). one or two weeks ago i've also noticed a support request on the drupal slack by someone trying to get the add-on work (who had basically the same issues like me). so based on my own experience as well as the details i've learned during the conversation on slack i've tried to come up with a few improvements to the README.md: 

- added a TOC and structured the entire document with headlines
- untwine the long codeblock at the beginning and move the different parts into the appropriate sections
- tried to make it clear nothing should be installed (required) with composer like for example drush (therefore the warning box to make it extra clear)
- added the omit the database container flag since the addon is using SQLite (to save a few megabyte but at the same time to help the user to understand how the add is working and what database is used - which is also relevant in case someone wants to drop the database tables in case one is working on a patch in the context of the drupal installer).  
 
plus i've added the suggestions @rfay made over on the old PR into this one

2024-03-27 06:53 UTC, T-Fletcher commented on README.md
> +* [PHP Unit](#install-drupal)
These IDs will need updating to work

2024-03-27 06:53 UTC, T-Fletcher commented on README.md
> +* [Nighwatch](#install-drupal)
Same again here

2024-03-27 06:56 UTC, T-Fletcher reviewed
Looks like #17 was merged in, you may want to rebase this so we don't double up on changes. In particular, @rfay's line about running DDEV with preset flags for overrides, php version etc. 

Given my #16 was getting messy, I'm happy to work on this one instead as we're working towards the same goal.

2024-03-27 15:30 UTC, rpkoller commented
> Looks like #17 was merged in, you may want to rebase this so we don't double up on changes. In particular, @rfay's line about running DDEV with preset flags for overrides, php version etc.

thank you, i've rebased my branch against upstream/main now. i was under the impression since the github ui showed that the branch has no conflicts with the base branch it wouldn't be necessary. but definitely the better and cleaner choice.  

> Given my #16 was getting messy, I'm happy to work on this one instead as we're working towards the same goal.

i think we shouldnt expand the scope and pack more things into this PR. I would keep this PR about simply restructuring the README to improve hopefully readability and clarity. The PR you have started is more about functionality and that the quickstart guide runs through without any stumbling blocks. 

And in regards of the continuing problems  #16  and also #20 @simesy tried to fix alongside the changes in the upcoming version 1.23.0 of DDEV https://github.com/ddev/ddev/releases/tag/v1.23.0-alpha1 @rfay suggested in a conversation on slack to do the following: 

```
I think that the 3-4 contributors trying to sort things out in the justafish repo should just sit down and collaborate. Slack channel for that might not be a bad idea. Competing PRs are just going to waste justafish’s time and energy```

that was the reason behind simes posting: https://github.com/justafish/ddev-drupal-core-dev/issues/22

so you are welcome to join the discussion on the newly created channel.

2024-03-27 22:10 UTC, T-Fletcher commented
Sounds like a smart approach, I agree with trying to keep functionality vs readability separate but note this can be messy when we are working on the same files via separate PRs. 

What's the Slack channel called?

2024-03-27 22:26 UTC, rfay commented
See 
* https://github.com/justafish/ddev-drupal-core-dev/issues/22

@T-Fletcher

2024-04-27 20:00 UTC, rfay requested changes
Thanks for this, it's going to be great. 

Minor suggestions. Should go in ASAP.

2024-04-27 20:00 UTC, rfay commented on README.md
> +* [PHP Unit](#php-unit)
```suggestion
* [PHPUnit](#phpunit)
```

2024-04-27 20:00 UTC, rfay commented on README.md
> +> :warning: There is no need to `ddev composer require drush/drush` to get the ability to for example clear caches. A subset of that kind of functionality is available with `ddev drupal list`. Otherw
```suggestion
> :warning: To avoid unstaged conflicts in git, **do not** `ddev composer require drush/drush`.  A subset of that kind of functionality is available with `ddev drupal list`.
```

2024-04-27 20:00 UTC, rfay commented on README.md
> +In case you need to drop your database tables because you are for example working in the context of the Drupal installer you can simply manually delete the SQLite database file located in `sites/defa
```suggestion
To drop your database tables, for example if you're working in the context of the Drupal installer, manually delete the SQLite database file located in `sites/default/files/.sqlite`.
```

2024-04-27 20:25 UTC, rpkoller commented on README.md
> +Because `ddev-drupal-core-dev` is using SQLite the database container could be omitted on `ddev config --project-type=drupal10 --omit-containers=db`.
In this comment I try to explain "why" the `--omit-container` flag was actually used.

2024-04-27 20:35 UTC, rfay requested changes
Noticed problem with `ddev corepack`, which isn't a thing. I don't think we even have to do this when the other PR goes in.

2024-04-27 20:35 UTC, rfay commented on README.md
>  ddev corepack enable
```suggestion
ddev exec corepack enable
```

2024-04-27 20:35 UTC, rfay commented on README.md
> +Because `ddev-drupal-core-dev` is using SQLite the database container could be omitted on `ddev config --project-type=drupal10 --omit-containers=db`.
IMO it would be better to do that in a comment above the command. Here it's out of context.

2024-04-27 20:35 UTC, rpkoller commented on README.md
>  ddev corepack enable
as i've mentioned on discord. `ddev config --omit-containers=db --disable-settings-management` is the exact line used on @simesy's PR. the only overlapping line. therefore i've adjusted it here to avoid conflicts and hassle. and i think those two flags are still needed. for one to avoid the db containers plus to disable the settings management. the rest is done bei config --update

2024-04-27 20:39 UTC, rpkoller commented on README.md
>  ddev corepack enable
in regards your corepack suggestion. all the quickstart commands i havent bothered. all of those are taken care of in simes PR. and that corepack line is obsolete and not necessary anymore. config --update takes care of that.

2024-04-27 20:41 UTC, rfay commented on README.md
>  ddev corepack enable
Oh, that PR removes this line? OK. But at least it could be correct. There isn't a `ddev corepack` anywhere. All good.

2024-04-27 22:53 UTC, rfay approved these changes
Thanks, it should be fine! I'd rather have `ddev exec corepack enable` if it's going to be there at all but we can wait for that.

2025-03-15 04:35 UTC, closed without merging