Updated CLI steps to handle settings.php being created early by ddev
justafish/ddev-drupal-core-dev pull request #16
Opened 2024-03-23 13:39 UTC by T-Fletcher

This patch makes a few tweaks to streamline initial installation:

1. Adds prerequisites with links.
2. Removes `sites/default/files` and `sites/default/settings.php` after `ddev` creates them when setting the project type - if they are present when `ddev drupal install` is run, Drupal errors saying it's already installed.
3. Sets the `yarn` version and enables `corepack`, see #12.
4. Adds steps to install `drush`, if desired.

2024-03-24 01:41 UTC, rfay requested changes
Some things to smooth things out.

2024-03-24 01:41 UTC, rfay commented on README.md
> +It assumes you already have [DDEV](https://ddev.com/) and [Docker](https://www.docker.com/products/docker-desktop/) installed, and are familiar with using `git` to clone code repos via the command li
```suggestion
It assumes you already have [DDEV](https://ddev.com/) and [a Docker provider](https://ddev.readthedocs.io/en/stable/users/install/docker-installation/) installed, and are familiar with using `git` to clone code repos via the command line.
```

2024-03-24 01:41 UTC, rfay commented on README.md
> +ddev exec corepack enable
I think this should be done already by the add-on, super easy.

2024-03-24 01:41 UTC, rfay commented on README.md
> +ddev exec yarn set version stable
```suggestion
ddev yarn set version stable
```

2024-03-24 09:03 UTC, T-Fletcher commented on README.md
> +ddev exec corepack enable
@rfay I haven't tried running it without this line, if it's already being run I'll remove this. No point duplicating

2024-03-24 09:06 UTC, T-Fletcher commented
Thanks @rfay, I've accepted your changes.

2024-03-24 12:17 UTC, rfay commented on README.md
> +ddev exec corepack enable
No, I was saying that as a separate PR, the add-on can `corepack enable` either as a post-start hook or as a Dockerfile. I'll probably do a PR for that. I wasn't saying you should change anything here.

2024-03-24 14:11 UTC, rfay requested changes
Worked through it again :) Another round of suggestions. We need to get the add-on working though with yarn, see
* https://github.com/justafish/ddev-drupal-core-dev/pull/17

2024-03-24 14:11 UTC, rfay commented on README.md
> +ddev yarn set version stable
Instead, see https://github.com/justafish/ddev-drupal-core-dev/pull/17

2024-03-24 14:11 UTC, rfay commented on README.md
>  ddev composer install
Might as well do it all in one step.
```suggestion
ddev composer require drush/drush && ddev composer install
```

2024-03-24 14:11 UTC, rfay commented on README.md
> +ddev composer require drush/drush && ddev composer install
No longer needed
```suggestion
```

2024-03-24 17:13 UTC, rpkoller commented on README.md
> +ddev composer require drush/drush && ddev composer install
```suggestion
```

drush shouldn't be required/installed here, that is making changes to the composer.json and you will never have a clean 11.x main branch since drush is not part of core. changes to the composer.json should only happen on a feature branch if a dependency is updated to a newer version or newly added. that is also the reason why you have the `ddev drupal cache` available from within the addon. i've added some words of caution in regards of composer require and drush in particular to my suggested changes for a PR i've created a few days ago: https://github.com/justafish/ddev-drupal-core-dev/pull/13

2024-03-24 17:13 UTC, rpkoller commented on README.md
> +# Install Drush (recommended, use with `ddev drush <command>`)
```suggestion
```

2024-03-24 17:13 UTC, rpkoller commented on README.md
> +ddev composer require drush/drush && ddev composer install
oh and i just noticed that `ddev composer install` was run before so the entire line could be removed imho

2024-03-24 21:07 UTC, rfay commented on README.md
> +rm -rf sites/default/files && rm -f sites/default/settings.php
There's no harm removing an existing .sqlite.

2024-03-24 22:08 UTC, rpkoller commented on README.md
> +rm -rf sites/default/files && rm -f sites/default/settings.php
but the .sqlite file will just be created when `ddev drupal install` is executed. at this point (in line 16) this command has no effect since there is no .sqlite file yet.

2024-03-24 22:11 UTC, rfay commented on README.md
> +rm -rf sites/default/files && rm -f sites/default/settings.php
UNLESS somebody is re-using the directory, which I often do. That's why I suggested it.

2024-03-24 22:17 UTC, rpkoller commented on README.md
> +rm -rf sites/default/files && rm -f sites/default/settings.php
hm but the readme is intended for someone starting for the first time, reading the `rm`line i consider rather confusing. but for cases like reusing the directory as well as if you are working on the installer and you have to drop the database i've added a note for on here: https://github.com/justafish/ddev-drupal-core-dev/pull/13/files in line 42

2024-03-25 10:57 UTC, T-Fletcher commented on README.md
> +ddev composer require drush/drush && ddev composer install
Good point about Drush, I hadn't considered that. If the intent here is to have a totally clean codebase then it shouldn't be included, but perhaps instead a note should be added that explains why it's not present despite being such a common tool for Drupal development.

2024-03-26 06:32 UTC, T-Fletcher commented
It may make more sense to apply my changes after #17 is resolved, as it overlaps. I also personally preferred @rpkoller 's README in #13, much easier to digest for newcomers :) Shall we continue this work in those tickets?

2024-03-26 13:35 UTC, rfay commented
* #17 is in.

2024-03-27 11:31 UTC, simesy commented
Different approach (I hadn't read this PR closely and my solution has different things, ironically) https://github.com/justafish/ddev-drupal-core-dev/pull/21

2024-03-27 12:53 UTC, rfay requested changes
Ooops, I see I didn't finish my review. The fix here with sites/default/files on a mutagen-enabled system is important.

2024-03-28 13:18 UTC, closed without merging

2024-03-28 15:50 UTC, rfay commented
A couple of suggestions @T-Fletcher - 
* Please use a named branch for PRs, so you don't get messy with trying to use "main" for various things. It always comes out badly. Use a branch like "20240328_fix_drupal_install_errors" or something like that.
* When you close a PR without merging, please don't delete the branch. It loses all the changes.

2024-03-28 23:36 UTC, T-Fletcher commented
Thanks for the advice @rfay, this as my first time working with multiple devs on the same issue. I'll be sure to use feature branches and preserve the work even when closing the MR. Thanks!