Prepare for DDEV 1.23 and improve initial config.
justafish/ddev-drupal-core-dev pull request #23
Opened 2024-04-08 09:56 UTC by simesy

This PR prepares the plugin for ddev 1.23 and also is a little more explicit about its config including setting some initial config to make sure ddev inits correctly.

**Please note** that if you want to **reinstall Drupal.** there is a known issue with the sites/default being hardened and it's not obvious the user how to reset drupal. A future PR will fix this.

2024-04-08 11:04 UTC, simesy commented
@rpkoller says a remaining issue is restarting ddev.

2024-04-08 11:15 UTC, rpkoller commented on web-build/Dockerfile
> -RUN corepack enable
Readding `RUN corepack enable` is necessary otherwise corepack is not available after the restart. `ddev exec corepack enable`ran in the install.yaml has no effect after a restart and you get 
```
$> ddev yarn --version
1.22.21
```
in the project root as well as the core folder.

2024-04-08 12:42 UTC, simesy commented on web-build/Dockerfile
> -RUN corepack enable
On 1.22.7

2024-04-08 13:00 UTC, rfay commented
One thought: If you want to make it require DDEV v1.23, which would make things simpler,  `config.*.yaml` could require DDEV v1.23+ by adding

```
ddev_version_constraint >= v1.23.0-alpha1
```

https://ddev.readthedocs.io/en/stable/users/configuration/config/#ddev_version_constraint

2024-04-08 13:01 UTC, simesy commented on web-build/Dockerfile
> -RUN corepack enable
I've added `RUN corepack enable` for 1.22.7

2024-04-08 13:07 UTC, rpkoller commented on web-build/Dockerfile
> +# Required for ddev restart on 1.22.7.
or maybe add the conclusion/reasoning in the parenthesis  in a brief shortened to the comment as well?

2024-04-08 13:22 UTC, rpkoller commented
> One thought: If you want to make it require DDEV v1.23, which would make things simpler, `config.*.yaml` could require DDEV v1.23+ by adding

it would be less jumping through hoops by simply requiring 1.23+ and it would also save users from the annoying redownload of yarn in 1.22.7

```
        Corepack is about to download https://registry.yarnpkg.com/yarn/-/yarn-1.22.22.tgz.

        Do you want to continue? [Y/n]
```

2024-04-08 13:32 UTC, rfay commented
> it would be less jumping through hoops by simply requiring 1.23+ and it would also save users from the annoying redownload of yarn in 1.22.7

If I'm not mistaken, it will only save users from this the second and following times. The reason is that DDEV v1.23+ sets the COREPACK_HOME to a persistent volume, so yarn is there there the next time it's looked for, unless, of course, the yarn version has changed and a new one has to be fetched.

2024-04-08 13:54 UTC, rpkoller commented
yep in my tests on 1.22.7 you had to redownload yarn after every restart of the project.

2024-04-09 03:10 UTC, simesy commented
Either option suits me. If this was a plugin that people used for their paid work then I would question forcing them to upgrade. Any performance improvements can be follow up. 

Happy to act on instruction.

2024-04-26 12:54 UTC, pcambra commented
Just adding the woraround from @stasadev on https://github.com/ddev/ddev/issues/6110#issuecomment-2061093254

1. Create a file `.ddev/web-build/Dockerfile.sqlite`
2. The file should have this content:
```
ARG TARGETPLATFORM
RUN SQLITE_VERSION=3.45.1 && \
    mkdir -p /tmp/sqlite3 && \
    wget -O /tmp/sqlite3/sqlite3.deb https://ftp.debian.org/debian/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && \
    wget -O /tmp/sqlite3/libsqlite3.deb https://ftp.debian.org/debian/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && \
    dpkg -i /tmp/sqlite3/*.deb && \
    rm -rf /tmp/sqlite3
```
3. `ddev restart`

2024-04-27 03:47 UTC, rpkoller commented on web-build/Dockerfile
>  RUN sudo apt-get update && sudo apt-get install chromium-driver -y
```suggestion
RUN sudo apt-get update && sudo apt-get install chromium-driver -y

ARG TARGETPLATFORM
RUN SQLITE_VERSION=3.45.1 && \
    mkdir -p /tmp/sqlite3 && \
    wget -O /tmp/sqlite3/sqlite3.deb [https://ftp.debian.org/debian/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb](https://ftp.debian.org/debian/pool/main/s/sqlite3/sqlite3_$%7BSQLITE_VERSION%7D-1_$%7BTARGETPLATFORM##linux/}.deb) && \
    wget -O /tmp/sqlite3/libsqlite3.deb [https://ftp.debian.org/debian/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb](https://ftp.debian.org/debian/pool/main/s/sqlite3/libsqlite3-0_$%7BSQLITE_VERSION%7D-1_$%7BTARGETPLATFORM##linux/}.deb) && \
    dpkg -i /tmp/sqlite3/*.deb && \
    rm -rf /tmp/sqlite3
```
the snippet for upgrading SQLIte to 3.45.1 suggested by @stasadev on https://github.com/ddev/ddev/issues/6110

2024-04-27 19:31 UTC, rfay requested changes
I think it's really important to get this over the finish line ASAP so we'll have it mature and released by Drupalcon Portland a week from now (May 5). 

Tested with:

```
ddev get https://github.com/simesy/ddev-drupal-core-dev/tarball/main
```

It does require @rpkoller's .ddev/Dockerfile.ddev-drupal-core-dev changes to get Sqlite3 3.45

2024-04-27 19:31 UTC, rfay commented on config.ddev-drupal-core-dev.yaml
> +ddev_version_constraint: '>=v1.23.0-alpha1'
Might as well be v1.23.0 now.

```suggestion
ddev_version_constraint: '>=v1.23.0'
```

2024-04-27 19:31 UTC, rfay commented on web-build/Dockerfile
>  RUN sudo apt-get update && sudo apt-get install chromium-driver -y
Now that there's a config file, move the chromium-driver to the yaml file.

2024-04-27 19:31 UTC, rfay commented on config.ddev-drupal-core-dev.yaml
> +
```suggestion

webimage_extra_packages: ["chromium-driver"]
```

2024-04-27 19:31 UTC, rfay commented on config.ddev-drupal-core-dev.yaml
> +upload_dirs:
```suggestion
upload_dirs:
# The install technique tries to remove all of sites/default/files
# but with DDEV + mutagen that isn't possible.
# so just redirect the upload_dirs.
```

2024-04-27 19:31 UTC, rfay commented on install.yaml
>    - web-build/Dockerfile
```suggestion
  - web-build/Dockerfile.ddev-drupal-core-dev
```

2024-04-27 19:33 UTC, rfay commented
@justafish if you could also run the workflow it would be great. Or give perms to me to do it. 

I'm assuming this add-on has a bright future, right? Do you want to move it to official in the `ddev` org? You'd remain maintainer.

2024-04-27 20:21 UTC, rpkoller commented on web-build/Dockerfile
>  RUN sudo apt-get update && sudo apt-get install chromium-driver -y
updated the snippet from @stasadev (still dont know what changed it) and also removed the entire line 4 with the two apt-get commands per your recommendation

2024-04-30 22:01 UTC, rfay approved these changes
@justafish if we can get this in then I'll add to it support for drush and automatic setup of the proper SIMPLETEST_DB info in the phpunit.xml. I'll open an issue about drush explaining how I'd like to do it.

2024-05-01 04:14 UTC, simesy commented
Closed in favour of https://github.com/justafish/ddev-drupal-core-dev/pull/30 as i changed the base branch in the forked repo to `upstream`.

2024-05-01 04:14 UTC, closed without merging

2024-07-30 16:00 UTC, prashantdsala commented
Has this been fixed? I am on ddev version 1.23.3 and Drupal 11.x and still facing this issue. Can someone point me to the resolution for this?

Thanks

2024-07-30 16:27 UTC, rfay commented
Please use HEAD; a new release hasn't been done with several commits.
```
ddev get https://github.com/justafish/ddev-drupal-core-dev/tarball/main
```

There are also other PRs pending that may be useful to you. Most of them have instructions how to `ddev get` them.

2024-07-30 16:36 UTC, prashantdsala commented
Thanks.

Tried the following commands by taking reference from https://github.com/justafish/ddev-drupal-core-dev/commit/cd06f6cea7781286c769dc4129ed672bb29c316f but did not help:


`ddev config --omit-containers=db --disable-settings-management
ddev start
ddev get justafish/ddev-drupal-core-dev
ddev restart
ddev composer install`

2024-07-30 16:43 UTC, rfay commented
I hope you didn't do those all on the same line. 

But could you please use what I said in https://github.com/justafish/ddev-drupal-core-dev/pull/23#issuecomment-2258746104 ? You're getting the released version of this add-on, which is quite old. I'm sorry, I don't have access to create a release. (And please open a new issue in situations like this instead of commenting on an old PR)